theme: minima
title: LoniBoni
author: Loni
email: Loni@masiero.us
description: > # this means to ignore newlines until "baseurl:"
  Meow Meow Meow

# social links
instagram_username: loniboni22 # DO NOT include the @ character, or else the build will fail!
github_username:  lmasiero22 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
