title: LoniBoni
author: Loni
email: loni@masiero.us
description: > # this means to ignore newlines until "baseurl:"
 Meow Meow
# social links
instagram_username: Loniboni22 # DO NOT include the @ character, or else the build will fail!
github_username:  lmasiero22 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
